import '@storybook/addon-actions/register'
import '@storybook/addon-knobs/register'
import '@storybook/addon-links/register'
import '@storybook/addon-storysource/register'
import 'storybook-addon-specifications/register'
// import './addons/tests.js'
// import 'storybook-addon-jsx/register'
